### ISSUE TITLE
Amy is the phantom ruby in competition results and the game crashes in cpz2 on random moments in comp. mode as amy

### ISSUE THREAD

**Issue by SonicGamerEpisode55** [Kiaru-the-Fox/Sonic-Mania-Addendum#2]
Amy is the phantom ruby in competition results and the game crashes in cpz2 on random moments in competition mode as amy
Linux, OGL, GNU gcc, CMake

**Comment by Kiaru-the-Fox** [comment]
I've fixed the Competition portraits issue (and it turns out it was also affecting Mighty and Ray as well!), but I haven't been able to replicate this crashing issue in CPZ2 Competition Mode.
