### ISSUE TITLE
Assorted Bugs

### ISSUE THREAD

**Issue by Pinkanator** [Kiaru-the-Fox/Sonic-Mania-Addendum#3]
Left some of these over on SHC but I'm not sure you noticed?

-As others have pointed out, Knuckles, Ray and Amy have issues with their glide interfering with the re-curl, causing animation bugs

-Heavy King's palette is borked in Lava Reef 2K

-Knuckles is sent to Mirage Saloon Act 1, rather than his personal Mirage Saloon Act K

-Mighty is sent to Mirage Saloon Act K, which he cannot actually complete and this cannot be remedied due to incompatability issues by restoring his Wall Kick

-Super Amy has her jump gimped when jumping out of water, not sure if it's JUST her, a lot of variables to test there.

**Comment by Kiaru-the-Fox** [comment]
I've been able to fix all of these except for the Super jump height issue, as I'm not entirely sure where that bug is coming from. Thank you for reporting these!

**Comment by Pinkanator** [comment]
Happy to help! Looking forward to updates, this mod is really wonderful and you're doing such a great job!

**Comment by Kiaru-the-Fox** [comment]
A bit of an addition to my last comment, but I actually have added Mighty's wall kick ability to Addendum natively, so in theory even if Mighty was still thrown into Knuckles' MSZ1, he would be able to complete it now.

**Comment by Pinkanator** [comment]
Ah! Lovely! I was hoping that was possible! I had a few suggestions I left on SHC but felt they weren't worth putting in a bug report and such. (Really I'm mostly hoping MSZ1E can be optional, but I've no idea how taxing a task that would be)
