### ISSUE TITLE
Why no commits? The last issue is marked as fixed.

### ISSUE THREAD

**Issue by SonicGamerEpisode55** [Kiaru-the-Fox/Sonic-Mania-Addendum#4]
A while ago, I've checked some things in the repo and no commits have been added.

**Comment by Kiaru-the-Fox** [comment]
I have the changes fixed on my local repository, I just haven't pushed them out yet, that's all.

**Comment by SonicGamerEpisode55** [comment]
Can you push them? i can't play the game because Mighty getting to the MSZ K path
