### ISSUE TITLE
Can you push new changes? i can't play the game because Mighty getting to the MSZ K path

### ISSUE THREAD

**Issue by SonicGamerEpisode55** [Kiaru-the-Fox/Sonic-Mania-Addendum#5]
Just playing the game as Mighty and I can't play Mirage Saloon because Mighty is going the Knuckles path.

**Comment by Kiaru-the-Fox** [comment]
I can't just push the current build I have as-is, because it's an unstable indev version of the mod. You'd have to wait until the next release version of Addendum comes out.

**Comment by SonicGamerEpisode55** [comment]
Ok.

**Comment by SonicGamerEpisode55** [comment]
So: Can you push the changes to the indev branch?

**Comment by Kiaru-the-Fox** [comment]
I made the indev branch under the assumption that branches could be private, so it isn't meant to be publicly available. The indev branch is intended for Addendum's developers to share current and in-development code. Making this unstable and indev code publicly available will only cause me more issues.
Also, can't you just use the dev menu to set the stage to MSZ1? That is a much simpler fix than demanding that I push highly untested code for you just to fix a small issue.
