### ISSUE TITLE
Hammer Jump and Heli-Hammer broken as Tiny Amy

### ISSUE THREAD

**Issue by hellduck64** [Kiaru-the-Fox/Sonic-Mania-Addendum#8]
I just did a full playthrough of the mod as Amy with the standard moveset, and i found that in MMZ2 you cannot use the Hammer Jump while shrunk. Attempting to do so locks you on the spot in the first frame of the animation. Getting hit takes you out of the locked state but in any case the ability is unusable in tiny form. Plus i found that the Heli-Hammer works but it does also gets stuck on the first animation frame.

Extra info:
RSDKv5U on x86_64 Linux
I played the SHC2023 build of the mod but i compiled Addendum's Game.so from source.

**Comment by Kiaru-the-Fox** [comment]
Thank you for reminding me of this issue, I often forget the Chibi character stuff is a thing. I'll look into fixing this for the next release!

**Comment by Kiaru-the-Fox** [comment]
Turns out I had left in an unused animation ID for the Chibi Amy animation file that isn't present in the normal Amy animation file. Deleting the "Unspin" animation and saving the file should fix these issues.
