### ISSUE TITLE
Crash before entering Main Menu

### ISSUE THREAD

**Issue by hermaherp** [Kiaru-the-Fox/Sonic-Mania-Addendum#9]
**Issue:** The game hangs and crashes when attempting to load into the main menu

**Target version:** RSDKv5U - All (x64)

**RSDK version used:** [Commit 64df5c1](https://github.com/Rubberduckycooly/RSDKv5-Decompilation/commit/64df5c1b3cb0583e2f88a4b8a909294e4e15cbdb)

**Graphics API:** DX9

**Addendum version used:** [Commit 546ab35](https://github.com/Kiaru-the-Fox/Sonic-Mania-Addendum/commit/546ab35251298db5eadd4ced9adc9ee2c5254d3e)

**Description:** I compiled the RSDK executable with version 5U (specifically targeted at 5vU - All) and I use it with a Data.rsdk from my Sonic Mania Plus game folder. I compiled Addendum targeting that same version and made sure that the branches were Release and x64 on both projects. When I copy the resulting Game.dll from Addendum, as well as adding the mod folder and setting it up, the game crashes even on a fresh folder without config or saves when I try to load into the main menu, effectively locking me out of playing the game

**Comment by Kiaru-the-Fox** [comment]
Do you have the Addendum mod itself enabled via the mod loader?
It requires that you have both the code (Game.dll) and assets (mod loader mod) loaded simultaneously to work.

**Comment by hermaherp** [comment]
Yes, the mod is enabled as per the setup instructions previous to executing the game

**Comment by Kiaru-the-Fox** [comment]
Could you try using the v5U Game.dll file and assets from [Addendum's SHC release page](https://shc.zone/entries/contest2023/917)?
I'm not entirely certain if the code on this repo here is completely functional, but I can say for certain that the SHC release is.
Try using that, and if you still have issues, and if possible, contact me via Discord (@kiaragale).

**Comment by hermaherp** [comment]
Will do
